apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  dependsOn:
    - name: helmrepositories
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./crds
  prune: true
