apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helmrepositories
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./helmrepositories
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
