apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:f8AVRXo=,iv:VHbaMq37zZxj1+xkd9vRFaQ8PpKSC5AKxs09MdHUdhg=,tag:CljWYzpqCMw0bKbLTewqhg==,type:str]
    admin-password: ENC[AES256_GCM,data:K9pmHaDl5oDsWDVKYoM=,iv:CGaL4b5lYe6l1iolNz7+X2tQYa/0qaDGFGlcqFG3/xE=,tag:DvydCEhrW2EWnNJ3HjssUQ==,type:str]
sops:
    lastmodified: "2025-08-29T14:36:37Z"
    mac: ENC[AES256_GCM,data:0jekXnsEbt7kkvZvK6PZQ0c36FAEvTSREIcxWuppkOVwA7zgnIQkYuqNicEeYwtRu5arg/4aIyT7Jmd1t4bu/hKB0o9iy25IE4lr9JV03tM+4unJla1vpQSqTxYRdfWmXa4ifJfXTYoTpyBINR9ybpW8HWqNA1m8MImaSL11bn4=,iv:5xCdZGzbUZt8ZDqns4zTA07eGMc3cEWbOM1DFkZlawM=,tag:6QjF1C8j2ZTyRmuzndb/wA==,type:str]
    pgp:
        - created_at: "2025-08-29T14:36:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA17PYeqLyQPSARAAjJHSL+2K87CuQeBzrJKrsQwOKsgLNIhdJSQsPxcTCeJM
            awpKl8cImwDAWi56GTdaEKmfkBDFUlp/emG2qiTxvPVwv7T+2cV3dsGg7EQQFfau
            19jxwaJo6/AEksQ0sgCaSC3FVxvPUf9rdY1iydf7RijfyRR+d2YW1QCzXxlPvgSc
            LNkSw7ZkGNgiMKv3WZoRX+5gWJ+kGAPmtqTsyueldnHyOBssFuuTRGBs/HNPFddk
            86W6H/vL1Wx/BjiD+5WgzEN9Kv9qVN17HX5lLPYITK+/ssZl9j9WrPwl3TuUr07b
            Xkxd8FG7e/5Kk/32kTKuZfeOWY4FBRlo/0GwJ6Nct2pPIBAV/SyVLomavU9jWgVT
            9hlSSNM4sY4D/Yzal/AJ6XLZML4V96J+YiFcMgAk0iLa7dWGMct9ebw5IlvzBP7W
            k6fiXW8A4dFZOaOT1zZ9UigjzV34dRHL+7tquhodPh5LniuHsORP5yc+U6HPVYrc
            D+fRw353hU2MP8BO4cd3ZPXYENbE6KFejRgOu+mFwCTn0Ii0cvI8gWHeZlLGNEVM
            weCN90OWlJ8AmJqE2ssr+A5ItV/hXkA5p+hLLoue+gpbbNQRmB73RL9Wc2IyeICg
            YS5hja/iRXo6f4uLT4sLIem/C+Fq4GG3rTbrHWHusB/tbeyyYSlYaD2yD46B5irS
            XgF1nnSHTchcs4fyOOjrC95nhVjj5p4u5PXunaJCNmbGYjj2xtJILo4SoAe8m38Q
            1IbY+R62rM172n3mSGqfdvBDYRRC34J9kyDqj5G+ie73/hw7DxqR2sQKW9NJS2w=
            =mMbi
            -----END PGP MESSAGE-----
          fp: CFEB9CF1BBFB6A79F2CD7DF90A421F34D04D10E2
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.10.2
