apiVersion: v1
kind: Secret
metadata:
    name: alerting-github-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:toOHa2Ja2/LV2R7IvO9Jg5MVw+PJINsuzYUXfFtAf3iRm3nEw7z5Lw/Ti3qC2rM0Oc9aqwgQzARTxUIYPNBIi46qyAfGw8CRwGscGBvAUEdbKfKXI45PMes9FA66,iv:DR912ia75TeVVjMnQ1rkqg6Vm7r/tIiExQK9RaO39WQ=,tag:gGQnlTSP/5wxN4FgLVOTBA==,type:str]
sops:
    lastmodified: "2025-08-27T13:32:14Z"
    mac: ENC[AES256_GCM,data:CIuMY2vu9jU5KqzMHjVAAyx84UYXULDCItd/RtRPsFRNK88y721yJo4hE/58+tlqc+SpPkODkn+zWhYYY0NSVDYwOOazzrStMomjfh7y2n4lTSKPj3g24BC6jDwm5StWBiNQByK9ojvubIePpYAC3LMfsOnGLD91OVU4B3jcFvo=,iv:rNgX/LeH0i9/3rCdxvf0svaps6VcZtVAMb8toZY4rkI=,tag:xUPF8pjz6KFZkPKLzp/CFA==,type:str]
    pgp:
        - created_at: "2025-08-27T13:32:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA17PYeqLyQPSARAAvb1dNb23JNEUT30jxMBRj+5SoGujejxYxTTixQX4F91l
            /+pPFpKWQsf65B8+pfnzHZu3rv3cJ7O2gml1DDHKr99obNg2509KnJFUQiG6FQkd
            fhUh/bBbqohAyKGiEn3n64DR8rJkLX67zLuxNvnkh+svGixQeggmzbECa1dr0/zu
            oY09AkNQX2JDIHe+CyUcNUv3MnFxWuivHl6RisfNrOr4jbBYJQYoOiB1yubEeIIe
            6DkPBXUDwzkUmaPG8OrwwzNXXhN50clFkMBPaQHvAES1liUpEheN3oJ8C/S4EH6P
            B9grzfUzfLqm7ABHLpgivKpEoZa/v+CoxPpjbNiRIfgxT4pjxCGTbgtN1iMwP/PM
            Gcs2VBxXfPBwX2INq5pQ/SnxsbXPCWza+PNt4Unmlbx7YE1bxL2TYK7LJarzKU7T
            Cg94mY/DIMf+tr2ydJkc04ad3K1uQ2JrC6Sk0H0RBzTV/KJihkoYKgAjYRhGTrxx
            Kl+iK5c5OV+bh7TQEewq6j4neyjrAgEbxq4c0J9LW29hsQbnfdBCeXaTQvVnFkPH
            cLO0UxHWuyfX4p0utIKiIXWEPa1oQDTE+8DV8fwM7a4nUDn1tpUVc9vqkmN1yuZw
            s5nlUheFUk4vwQ4Ropjr/5ej8735oldveDkQ0yKWUYFKkUBymzlDw17DVPSlKwjS
            XgH3JLhQLl8iaA5qFRDYLS0US6ZN5I1FMTBCxqL9h8vm7HlgKxY3YTTVVW0aNxiO
            vXMUGwnI9TLxuv2XlwKrz62uLiMI3FRYOQQDK6ImHle4Uly1m4+1At35oq2/zqg=
            =xXZq
            -----END PGP MESSAGE-----
          fp: CFEB9CF1BBFB6A79F2CD7DF90A421F34D04D10E2
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.10.2
