apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  namespaceSelector:
    matchNames:
      - minio
  endpoints:
    - port: http
      path: /minio/v2/metrics/cluster
      interval: 30s
