apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:FOJwuyk=,iv:5PfmFY9wDiqfv4hSVfeQjC7bysRb7qxYPEfP6/ZG6s4=,tag:NOlN5XhaY+g2Pd4talLI0A==,type:str]
    password: ENC[AES256_GCM,data:HoqPzEFR/TezpUpMspTNKbE=,iv:08e976AF2jygrVMyRJbB5jsxBkjUFh3Qc5+nrg+d4Sw=,tag:lM6d9DR+EYgWcaLy2otB3w==,type:str]
sops:
    lastmodified: "2025-10-04T14:55:32Z"
    mac: ENC[AES256_GCM,data:RiUg0cidQ0/6kmMcFJPpCIwOyzAGATgQAspmTmpECWJAYSLXuGRgCpjcY/pP1F0ZKiEX5CDhkeKCoLCz9yEsB0X7uJWD8kSRq243sTTSvVL1ZKeJ0nsqS8pVLzDG3NWobg3/Kl8Fp+gdv5a4Q7XZTTCvcNHeVLECBWSArGpr+2Q=,iv:6zE6uhftut8gyINEsQq+OyjMHieCmHjCg2Z2TeEmMAk=,tag:0tBe1xG75GD/iWP7thR1TA==,type:str]
    pgp:
        - created_at: "2025-10-04T14:55:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA49FDTH2jIFGAQ//RIvw68ZlQUzwCx7iNw6+M9oVqFb/XU/aHx46+CvDIEQw
            s9R6yJeRyCLiCFgIgGcL12CKwcdcHFJQDEvDC9KzkfZqyJ6Cxso53xbVLfmdoJrx
            WVSckNSHT5mIYtGNVktU+49lqr25hA8FaNqmCG6zV60A7+tCMruleRKE+DJHQiOn
            hvjiySWO7gs0Gsa3DcUA1KIUjB4vlsemohSX+ssCmt6Zgsuxh2iXb34Vd7k20k8j
            BXA6N4Ms6yy+UrJ4eSkHdUHfdjs4rXIHVWbW8Jjg7IeXOIdtjDG0ZPO6dp0NVJnp
            j4w1rAX2y+DOzK/PCQQscUYmwUYt/QMh2iGmN8jAyxCzFMYP+s8pkQ454cDtFl/H
            E+OOA8tRcz4o8WD3nEDsbohfLFFhRwYErrEDDTVGJS2AEJdhfZ4ddgN8HoShG32B
            3MlOK2ZE9cpucPM0R9pZb13FheYvm+dwRwAEQPfb1LcHt2Rz90evP3cT9I/d0vpH
            nzE1Yq0cfYUJkK/5y4pGLA+biBlCGyLY9xC9jArfZOy7/GyNUOorTIJ6xcW7lOpt
            7M0ICBDbyx6q9TCmhCJkzRw+NgE+BY0ijSu2Mt58veBNQI1Kszy1GWWIt2oo9wRM
            n5mbnw2N0EhU4Z5ySqPwllvHB6/K78oNgeCj1RkMMeLUYrd9FfyyS3JvNe5M1qrS
            XgHkgRv828e39LBNbgxg/8kvll9keK7sV23/9n4Z6ZmdONmOviIJdDAb6WbzOgM6
            k2wgbMb3qSOXjc+jKZ2wp2jKQJ07w3LqZYx/LXzIQqCxYKfXhqybNUAQ9JtOQpU=
            =v/68
            -----END PGP MESSAGE-----
          fp: 9CA5E024D20FAFF406A3DEF997FA133DF1875526
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.10.2
