apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin-secret
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2ImHvCo=,iv:4GMCOfbkSgLIvLJ9RPP74wBk4StbmwqtajAtxnG5QTM=,tag:clkOJO3wxPHSl9ruOCqKAw==,type:str]
    password: ENC[AES256_GCM,data:Xmgj5hxQl4PYL8+ugnaFbe0=,iv:KVpPMCjyUj8FJKiEGr4++KS/VJ9gmaQPQpm8YxANCWg=,tag:4EA0BEYpxr0IdoFN/33uPA==,type:str]
sops:
    lastmodified: "2025-10-03T10:54:15Z"
    mac: ENC[AES256_GCM,data:eOaKpXLDcQrx0Thu/jJOrao5VcbOjYOQEHb3mfbJbiNRotwIXoAc7MDnDAsualj/fHxCDN2zFe+CvKmpe553/6w5FixoCHjDrtyQc5/O9Xhdswo3Xx22JJsOZ80YpWTuxTx8Z0EbBCGknZIIa9rvuQxrMzZUSEDuwZOHCvv8v38=,iv:Y3yKE063yNHC1gmNhSba6CsnLULNsd3MTNyxnXBP35Y=,tag:8zMWghMdxOOHYR9DHRfR+g==,type:str]
    pgp:
        - created_at: "2025-10-03T10:54:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA17PYeqLyQPSARAAvyjLgcVo+/oC8uEI++auYceHiYnoR3pSKqXpptD6/3GG
            MIOFWQFe5uyGgrPIpgLIw7uIyyIjO5i7tX9SoAO/Skqe0X8Q4wmT6+hmERIW7WaX
            xegAhmqd4AZ68IfXghzpSQ4D+xvO84k+5NQ7Usj9p2DapwH3zR0t/5S7hxRufasd
            D9uyw3R7Tzf/V/wR7szTq4ZeXStZvXk2y51bNPHXdF2H3I9MAghlsQwwQiCZoxKZ
            7UgRZ6yioNA36/ARNw9mlruBiJ4T5iEbeGDIQYl/gkf5o7SMgwCk3pKzJmPBwV2m
            m/d+OJ2vXkjx5JSghuMsCLtR5sIY70b/SWYCt2wgdkxM7kWpJVAG7cZuqjREnZvf
            6QiwPLuqdFTTH+NneHy4LioUxVMFoCb8IyLWtYmFFttDVK1M8L0FeQnyEm9zqpHZ
            rGNSuLFAOv87WNCCBMQgyfYHOd90W0tn6lGdq+VEtkrDNXBTGtpkzh3/PpxpXxN0
            ATMFOK6KqeF2uhSK9eEDEyiBnLkrb9kabI7lMbOthY3qCIt0zQ68j/UNwyWnCXwW
            JcKNjcNXzIIXMnO7fak40oOUGHxGIBVX1q8RMzDeCjcuPwtrlkfmUYQdQdW4XhKI
            zIcbSCiuArPzGJz7dLp8lTWIGBZLglafaHmcYMFwBh5Iv/HhnzL6cIQbcOgHtufS
            XgECCDvbIwvOAy3t5snhFe45qiHoR+rEcasAoVTQ8HqjofzyHbY0qIBhUcJuXEtE
            W82wBRbypgz4C/sTy0oGm0775Mw9NbP8+ZjMV44SYQ2NTTIHf5RaPtqcBSemag0=
            =ZPnl
            -----END PGP MESSAGE-----
          fp: CFEB9CF1BBFB6A79F2CD7DF90A421F34D04D10E2
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.10.2
