apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-storage
  nfs:
    server: nas.internal
    path: /mnt/minio1/data
  mountOptions:
    - nfsvers=4.2
    - hard
