apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helmreboot-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: helmreboot-operator
        namespace: flux-system
  values:
    # Only non-default values that we want to customize
    controllerManager:
      manager:
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
    
    # Enable Prometheus monitoring
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus: kube-prometheus-stack