apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/environment: prod
---
apiVersion: v1
kind: Service
metadata:
  name: notification-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/environment: prod
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/environment: prod
---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: flux-system
  labels:
    app.kubernetes.io/environment: prod
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-controllers
  namespace: flux-system
  labels:
    app.kubernetes.io/environment: prod