apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 1h
  dependsOn:
  - name: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator
      version: "25.8.4"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: mariadb-operator
  values:
    ha:
      enabled: true
      replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  upgrade:
    remediation:
      retries: 3
