apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: metallb-pool
    namespace: metallb-system
spec:
    addresses:
        - ENC[AES256_GCM,data:ltXG0S7LVbimZk5r9C2MiDX73tCfx4go324WvBk=,iv:K5iN5fIVuwocP3fwq1HsbBGlP5ECnTYs8VH9ZMeVxSA=,tag:wvluS4blJQ5H4SGOL4CnCw==,type:str]
sops:
    lastmodified: "2025-10-11T12:19:58Z"
    mac: ENC[AES256_GCM,data:SYMeyKKih0YcMKcXnMlHfAKYUQqRctaWtMiVOEu+94koi45XvdxzKPga8lO7+zlIeV17PTswwVJk+sxCnPfT+Dmr2VWSZxVHFJ4zvjhuL1HR5oIYrbSjVfrX1p9I0hA7SkmmVYo5XuEYc5psGMYrKegvUGWNQUVr/zYo6uKRSjA=,iv:yuCJ1T+oChCEQ9zjiem0EXuPkA0KSnARzVmGY5xo+jk=,tag:6/35rjQ/FQfRWEMzC+MGnw==,type:str]
    pgp:
        - created_at: "2025-10-09T16:15:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA49FDTH2jIFGAQ//Y4zQM4mzt+gYmxP/AfImLPFqsBsCh0jubRCjJP/hAfQt
            EdjuEQ9F8EpZrJbu++233yN8qxik3yQXA4aP5FUQrIl6k8myXDYdIp6fu9NbIFaw
            0aOrSMrQOLpiWvUCUFU69qTiOUkWySRAObq2vQrXmo13qMXErJwk13oZXiRSj0hw
            rxIr+oFboK1L1u0qDSnFUaNvuOmqSbnSIeM3u0luKcnrPMPz85dE0l5vU1YgH0HT
            678esCAje9fU5b43XaifIuCzg1Zw6T8S4VgeNN7TbcfXSLZhgae0hKuckIoqQYWs
            Rcw3P/eYknA/EZVXOVCY20+Ibv/8fk8kamZVUZAm37lRpOyx1hZU3hn17yJ5hNhP
            u6jMx5HH4VPH59FZb3xWRA1RmEwvSbT5azQv7b5zZs0LSQqBt9C5xgEGPUCYeqpU
            n3KxR1lcKa5vU420mh3gEI7+XhCcGH+J0EeEimcFQ2/GTEW5ZMhJJrRn6QArgjGF
            m3eYGPU9aIcn94QFfriHz4NIbEvrix8anTGhUBVOOh3+RG/fQi1ANMZ25u24Cmej
            H7TZxWtg68JSdl4/o7WMhY4aqnlExkrS+k5HwzEpv7BZRsfR+mMnhYpSFpndnF5l
            3pz8Go2vmX5AtbGUYw04+ur/zknhqWlaC5F3ae2iKGt9oA8M1+yweTIoLw4P5dXS
            XgFNCS21DyUr8vQqWHklb3HWl+VDm3Z8NeW3igXt4XHc6rAcKhiv5Xm5C9MM8/vy
            COEziS5ZH1V35I9L91fHeigEinhn7orphnYDPKuW6cUjBhpiUAzsyWP4+ApvaS4=
            =+DEn
            -----END PGP MESSAGE-----
          fp: 9CA5E024D20FAFF406A3DEF997FA133DF1875526
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.10.2
