apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: metallb-pool
    namespace: metallb-system
spec:
    addresses:
        - ENC[AES256_GCM,data:k24UeGTjs4tcguCkkFO0vZYtLUAlQ0eLRf08sxc=,iv:omnkfMbyr5o11fUFYKAiWFApTPx+a331HmKsFtw2AL0=,tag:7Lp6AH1bp61QTLGD8qfQHQ==,type:str]
sops:
    lastmodified: "2025-10-12T16:16:20Z"
    mac: ENC[AES256_GCM,data:E+SkSrydtgQ+epLA5xPj5XokFqJoykRwURLDoIRy5UB2B54PYWuShRzMP7O5RppQ5ljfWil4PFkn36KeEwQBPFBwRwmakyx5LF3P/AR4ZB4npKv5qCIs+5he153a0eJuFvGIGdXUso5y6wA8dKgaSa2XkpCObEwl2IL3F+7ece4=,iv:96CMPQj0x4BkTGw5qi6weggEPDGbeF1W8LhJfhpnvNM=,tag:OwGN2zSM0Sd1rrNvn4Xb/Q==,type:str]
    pgp:
        - created_at: "2025-10-12T16:16:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA49FDTH2jIFGARAAwY0YNfd2TlxSQZsU29kSyvt8Nj4xfUifHgd1vkK1beRp
            MECnJtD7W7ux278//ZyQvKdPqIJtNox+InBo7e1Gvi3p8ZSjnmSFDpUixB6xth4g
            qKjMl0Wbr++MQ29Sr91h27FkANKRiD02YdjJZqKgyNjTHrY6YWoMfyqXzkzE9qX9
            96B8cxQCbUbY16lJdodSG/lmYw1EfgoqMFRJSKVmSzJIhah+ayigVqE8SxAlCw37
            ivaz/OYLlHi+y3qZw1I0JmyTcdGp430Vgfs3X/5vd1Wsf7WBAw5/RyUgnoxVMnqg
            KUDmv/1BpCr3d5pe8eeoD2KmRE8KtjMNbQaDjTmH2KLqOxPyS7BFsk2JUqUCanlQ
            EOl7mn59RHCiJCtFPh5O61tTgBSgRBWyrhJ2k1tSwvdBRow7cq1m2tbr55rKTDNG
            TlJ9HsUdhDgrKkISHz7enwfNBEbt7INpHpkL0FmI8FVxOIkW+tKJNZsV3M7BUw+O
            Gw1J4ETgLfewb+MEs7L7ju/tQWR6SpoAor0IJJkI/u2eL56jD+eGr43mqX30wPPL
            /lJBrcToIT+zrNan87nt4z2XOwjuz0af5BqCBzgxD8t0ury8PA7hzvarjI75m5OP
            Ql0/BpmnWzd+5IUC6fty67WpkfBkG+Wzt8DgnPTQDnFGSQ6dD4TBVoE1T/tXAw/S
            XgFXuLuvFNJNC3cyu4cNsmLul1ST8GtVuEVYA8u6NFSRUqREW0JS5WQctLjNrWLU
            IG8A90CUhoTw/SFuc0y6mOGN2dO5iDarH9jUT6+J6ul7K/MLVXuv76tE8YitU7c=
            =VUgo
            -----END PGP MESSAGE-----
          fp: 9CA5E024D20FAFF406A3DEF997FA133DF1875526
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.11.0
