apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - values-configmap.enc.yaml

configMapGenerator:
  - name: k3s-monitoring-dashboard
    namespace: grafana
    files:
      - my-dashboard.json=dashboards/k3s-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
