apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
  values:
    mode: distributed
    replicas: 2
    persistence:
      enabled: true
      size: 45Gi
      storageClass: minio-storage
    drivesPerNode: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
    existingSecret: "minio-auth"
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      path: /
      hosts:
        - minio.crulabs.internal
      tls:
        - secretName: ca-crulabs
          hosts:
            - minio.crulabs.internal
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      path: /
      hosts:
        - minio-console.crulabs.internal
      tls:
        - secretName: ca-crulabs
          hosts:
            - minio-console.crulabs.internal
    metrics:
      serviceMonitor:
        enabled: true
        includeNode: true
        additionalLabels:
          prometheus: kube-prometheus-stack
