apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  chart:
    spec:
      chart: nextcloud
      version: 8.4.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: nextcloud
      dependsOn:
        - name: nextcloud-db
  values:
    replicaCount: 1
    nextcloud:
      host: nextcloud.internal
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
      persistence:
        enabled: true
        existingClaim: nextcloud-data
      ingress:
        enabled: true
        className: nginx
        hosts:
          - host: nextcloud.internal
        tls:
          - secretName: ca-crulabs
            hosts:
              - nextcloud.internal
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-db-rw
      database: nextcloud-db
      existingSecret:
        enabled: true
        secretName: cnpg-app-user
        usernameKey: username
        passwordKey: password
    persistence:
      enabled: true
      storageClass: nextcloud-storage
      size: 3500Gi
