apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: kafka
spec:
  interval: 30m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.48.0
      sourceRef:
        kind: HelmRepository
        name: strimzi-helm
        namespace: kafka
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicas: 1
    watchAnyNamespace: false
    resources:
      limits:
        cpu: 1000m
        memory: 384Mi
      requests:
        cpu: 200m
        memory: 256Mi
