apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cert
  namespace: nextcloud
spec:
  secretName: ca-crulabs
  duration: 2160h   # 90 days
  renewBefore: 360h
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
  - nextcloud.internal
