apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 1h
  path: "./config/crd/bases"
  prune: false
  sourceRef:
    kind: GitRepository
    name: metallb
