apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - namespace.yaml
  - crds.yaml
  - metallb.yaml
  - metallb-pool.enc.yaml
  - l2-advertisement.yaml
