---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/metallb/metallb
  ref:
    tag: v0.15.2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 1h
  path: "./config/crd/bases"
  prune: false
  sourceRef:
    kind: GitRepository
    name: metallb
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-crds
  interval: 30m
  path: "./config/native"
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb

