apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-crds
  interval: 30m
  path: "./config/native"
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb
    namespace: flux-system
