apiVersion: v1
kind: Secret
metadata:
    name: hedgedoc-minio-creds
    namespace: hedgedoc
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:AO2EJW60BXi0tsdeqsGhEQQ3kzM=,iv:yYyWT3DTEjVpaALKUuCPxJrystBBs4hgwHLiMnzcBxs=,tag:+P/xwZdFTv2p0XSgWOQV6Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Bl13vrL14MibxhGBwI1iPqAvqpM1tHeNgwENMM/8h4WjouJOtAeGZQ==,iv:Y6TVMF4kbhM+cBR7w11GHpiAo/Gzez1AuqLHBpl/6bU=,tag:1I71vGZrGUioQu9PGpUsoA==,type:str]
sops:
    lastmodified: "2025-09-30T17:12:17Z"
    mac: ENC[AES256_GCM,data:vGV5n12aGZQyUbhv9nQC5kZNt2hbwMSUDOlmq8qnlvsJdKFtM4IfY3gDpVnUcrQXW+Lkkm7dBvHFWDHIQLXz1V0r1l/Y3xkC3ymDbvXJ7IBKJsKkpRqYpSl8Gzx+lCtdSudJi4nx8QB/fZLulYbNcaNthl3abc9TmMAmMlpMez0=,iv:5SYmXRNn6v1zlffJQkplEA8/QQoxX3jpuTedilaogJ0=,tag:oJUO6W4lOYRfVMn90iXbxA==,type:str]
    pgp:
        - created_at: "2025-09-30T17:12:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA17PYeqLyQPSAQ/8DC6Sc1roXhoA5fJ42Ec2r4AS7FuIuPTsMTaMxOZWsmBQ
            nJoSauAxQ50xl9B2csPEte4Ed+piwO1WHGLviaq0kMSCFPqVBuUkak1uggxTq0BZ
            FLfvrMUdcIxxCaRXmCLBGML8sCSYyIRG/wYIohEGCdLHX+tngIXrzBiBtD6q5LMr
            IasALl5XpWuzMrTGVkorbuViGFddlsSqCF+UiODBkExsKwouAgAUuAXWaRTJT/DX
            8IA9nTK8TCcPednUxXJdUzQSnsAspBpyOUYiNUoFm0MQud91xHZuiGogEnfE85p1
            +r8exUUfPktofqVDOIYI/nX4DmgRyVlWKtUesFVtxAZmooUutbd9m0QpaheCLGNl
            UgNmJ3HNAwZlZHL2nfwy0A2W9tZO0xGvKpXVX92YwYr2oe8PZxPpS3OqTfTdpiAL
            iirjk1X6czTTjxDs3Q9zYsrXCGK8leaiDY5T9xVL8/hwxavVYQX0H2daE1ek1Aqx
            d6whvj0hMib8kdhrJo4ycHDMCdUgHqZqA091DEIldx+kZCMnsQPUtUxKSX68ayrv
            TY+AOmfvGkWZk5wcMaMYM4oT9fwdRfZiZfi+NsWRp6z/6dtcGkPHs0ppsCqNQFtF
            +bGotVnGtfv/EJVGR/L+gST56L9KW3TVGNAXDVoytSHREntH44PesIjpAlu6qWDS
            XgHQ4gNrmH0ypHZ1dVhrok5FNlKm9xUz0lYLtJPN7JMYJdCWWMcNw2FVEvljGCg9
            SbDrEgeKlAv/o0YDjibrd+BWaF1/ij/6qJ7tLKHoruEIiz2f9S+TxTKAnbul0oU=
            =CkMh
            -----END PGP MESSAGE-----
          fp: CFEB9CF1BBFB6A79F2CD7DF90A421F34D04D10E2
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.10.2
