apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  interval: 10m
  chart:
    spec:
      chart: ./tenants/charts/cloudnative-pg
      sourceRef:
        kind: GitRepository
        name: local-charts
        namespace: flux-system
  values:
    initdb:
      owner: "admin"
      secret:
        name: "keycloak-cnpg"
    backup:
      enabled: true
