apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: codecentric
  namespace: keycloak
spec:
  interval: 1h
  url: https://codecentric.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  releaseName: keycloak
  chart:
    spec:
      chart: keycloakx
      version: 7.1.3
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
  values:
    replicas: 1
    image:
      repository: sleighzy/keycloak
      tag: "16.1.0-arm64"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    ingress:
      enabled: true
      ingressClassName: nginx
      rules:
        - host: keycloak.crulabs.internal
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ca-crulabs
          hosts:
            - keycloak.crulabs.internal
      console:
        enabled: true
        ingressClassName: nginx
        rules:
          - host: console.keycloak.crulabs.internal
        tls:
          - secretName: ca-crulabs
            hosts:
              - console.keycloak.crulabs.internal
    dbchecker:
      enabled: true
    database:
      vendor: postgres
      database: keycloak
      port: 5432
      username: admin
      existingSecret: keycloak-cnpg
      hostname: keycloak-db-rw.keycloak.svc.cluster.local
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        valueFrom:
          secretKeyRef:
            name: keycloak-admin-secret
            key: username
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-admin-secret
            key: password
