apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hedgedoc-db
  namespace: hedgedoc
spec:
  interval: 10m
  chart:
    spec:
      chart: ./tenants/charts/cloudnative-pg
      sourceRef:
        kind: GitRepository
        name: local-charts
        namespace: flux-system
  values:
    initdb:
      database: "hedgedoc"
      owner: "admin"
      secret:
        name: "hedgedoc-cnpg"
    backup:
      enabled: true
      destinationPath: "s3://hedgedoc/db/"
      endpointURL: "http://minio.minio.svc.cluster.local:9000"
      secret:
        name: "hedgedoc-minio-creds"
      retentionPolicy: "30d"
    storageClass: "local-path"
    storage:
      size: 5Gi
