apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hedgedoc-db
  namespace: hedgedoc
spec:
  interval: 10m
  chart:
    spec:
      chart: cluster
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
  values:
    cluster:
      instances: 2
      storage:
        size: 5Gi
        storageClass: local-path
      affinity:
        topologyKey: kubernetes.io/hostname
      monitoring:
        enabled: true
      initdb:
        database: hedgedoc
        owner: admin
        secret:
          name: hedgedoc-cnpg
