apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedgedoc
  namespace: hedgedoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hedgedoc
  template:
    metadata:
      labels:
        app: hedgedoc
    spec:
      containers:
        - name: hedgedoc
          image: quay.io/hedgedoc/hedgedoc:1.10.3
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hedgedoc-cnpg
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hedgedoc-cnpg
                  key: password
            - name: POSTGRES_DB
              value: "hedgedoc"
            - name: POSTGRES_HOST
              value: "hedgedoc-db-rw.hedgedoc.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "5432"
            - name: CMD_DB_URL
              valueFrom:
                secretKeyRef:
                  name: hedgedoc-app-config
          volumeMounts:
            - name: uploads
              mountPath: /hedgedoc/public/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: hedgedoc-uploads
