apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hedgedoc
resources:
  - namespace.yaml
  - secrets
  - cnpg-helmrelease.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
