apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hedgedoc-db-cluster-backup
  namespace: hedgedoc
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hedgedoc-db-cluster-backup-binding
  namespace: hedgedoc
subjects:
  - kind: ServiceAccount
    name: hedgedoc-db-cluster
    namespace: hedgedoc
roleRef:
  kind: Role
  name: hedgedoc-db-cluster-backup
  apiGroup: rbac.authorization.k8s.io
