apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
  namespace: ceph-csi
spec:
  releaseName: ceph-csi-rbd
  chart:
    spec:
      chart: ceph-csi-rbd
      version: "v3.15.0"
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: ceph-csi
  interval: 5m
  values:
    rbac:
      create: true

    serviceAccounts:
      nodeplugin:
        create: true
      provisioner:
        create: true

    csiConfig:
      - clusterID: a0f1d1f4-ac0f-4e4f-b06d-34e8deec52f8
        monitors:
          - "pve.crulabs.internal:6789"
        rbd:
          netNamespaceFilePath: "/var/lib/rancher/k3s/agent/kubelet/plugins/rbd.csi.ceph.com/net"
          mirrorDaemonCount: 1
        readAffinity:
          enabled: true
          crushLocationLabels:
            - topology.kubernetes.io/region
            - topology.kubernetes.io/zone

    CSIDriver:
      fsGroupPolicy: "File"
      seLinuxMount: true

    nodeplugin:
      hostNetwork: true
      hostPID: true
      kubeletDir: /var/lib/rancher/k3s/agent/kubelet
      imagePullSecrets:
        - name: ceph-secret
      initContainers:
        - name: setup-kubelet-symlinks
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              # Create symlink from /var/lib/kubelet to /var/lib/rancher/k3s/agent/kubelet if it doesn't exist
              if [ ! -d /host/var/lib/kubelet ] && [ -d /host/var/lib/rancher/k3s/agent/kubelet ]; then
                mkdir -p /host/var/lib
                ln -sf /var/lib/rancher/k3s/agent/kubelet /host/var/lib/kubelet
                echo "Created symlink: /var/lib/kubelet -> /var/lib/rancher/k3s/agent/kubelet"
              fi
              
              # Ensure plugins_registry directory exists
              mkdir -p /host/var/lib/kubelet/plugins_registry
              mkdir -p /host/var/lib/kubelet/plugins
              
              echo "Kubelet directories setup complete"
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-root
              mountPath: /host
              mountPropagation: Bidirectional
      plugin:
        image:
          repository: quay.io/cephcsi/cephcsi
          tag: v3.15.0
          pullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        volumeMounts:
          - name: plugin-dir
            mountPath: /csi
          - name: kubelet-dir
            mountPath: /var/lib/rancher/k3s/agent/kubelet
            mountPropagation: Bidirectional
          - name: sys
            mountPath: /sys
          - name: dev
            mountPath: /dev
          - name: lib-modules
            mountPath: /lib/modules
            readOnly: true
      registrar:
        args:
          - "--kubelet-registration-path=/var/lib/kubelet/plugins_registry/rbd.csi.ceph.com-reg.sock"
        volumeMounts:
          - name: registration-dir
            mountPath: /registration
          - name: plugin-dir
            mountPath: /csi
      tolerations:
        - operator: Exists
      nodeSelector: {}
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/rancher/k3s/agent/kubelet
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory

    provisioner:
      replicaCount: 1
      imagePullSecrets:
        - name: ceph-secret
      deployController: true
      fstype: ext4
      reclaimPolicy: Retain
      allowVolumeExpansion: true
      provisionerSecret: ceph-secret
      provisionerSecretNamespace: ceph-csi
      nodeStageSecret: ceph-secret
      nodeStageSecretNamespace: ceph-csi
      controllerExpandSecret: ceph-secret
      controllerExpandSecretNamespace: ceph-csi
    storageClass:
      create: true
      name: csi-rbd-sc
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      clusterID: a0f1d1f4-ac0f-4e4f-b06d-34e8deec52f8
      pool: k8s-pool
      imageFeatures: "layering"
      provisionerSecret: ceph-secret
      provisionerSecretNamespace: ceph-csi
      nodeStageSecret: ceph-secret
      nodeStageSecretNamespace: ceph-csi
      controllerExpandSecret: ceph-secret
      controllerExpandSecretNamespace: ceph-csi
      fstype: ext4
      reclaimPolicy: Retain
      allowVolumeExpansion: true
      mountOptions: []
    
    # k3s specific configuration
    kubeletDir: /var/lib/rancher/k3s/agent/kubelet
