apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml

configMapGenerator:
  - name: prometheus-values
    namespace: monitoring
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
