apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helmreboot-operator
  namespace: flux-system
spec:
  values:
    controllerManager:
      manager:
        image:
          # Fixed version for production stability
          tag: v0.1.0