apiVersion: v1
kind: Secret
metadata:
    name: minio-auth
    namespace: minio
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:aPV0IQI=,iv:Fuc1O/LYO5VT/58EYDBtTNpN+jT0wt8ymcT2cdzOpcg=,tag:4ZC3Mq14SXh8LcR0zDs6Lg==,type:str]
    rootPassword: ENC[AES256_GCM,data:7HAMq6w9tcw+a/jD8Y0BrhY=,iv:oq1H/K+K+ZCxlSa6XRRzWmwwHXrXqN9Q2Y6UdKCTNio=,tag:23jnG9WUzqx72qaJ1WR7iw==,type:str]
sops:
    lastmodified: "2025-09-27T20:39:27Z"
    mac: ENC[AES256_GCM,data:vfi6CiwfVI/mK6BY72Es5GGuEiN6CE5r4QBTh1xePB49RAhutJUDELhHRztvzJo8YHKonTQkb7EgEACZv821Q/wRvQ6cbuc65I2v6C2ZbtpcA2eSmDgGuV6PX4s4S3p+vMtfh9+sOw0+r+KamwdNYS9q4IZ4vz85mDA8vr9j8j0=,iv:DIxjBBED4qLoX40jd4mCTS2T9Bt6kDDRHx55fWv9ddw=,tag:C+qhYW+a0GM9uvyhzRdJTg==,type:str]
    pgp:
        - created_at: "2025-09-27T20:39:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA17PYeqLyQPSAQ/9FDMcTIuEbuCd/Eu2i+jCzdP62hgxzbr47Lqg3VWsCTWL
            KIUpMIFT+FNZsl/+SHFBBuzwrG+wUf0uQNEf3p6svl3ltxdicTLkdlHDq0eiCQuH
            8C9E69faxUA4/r18o08UZhwfkFrrb55lXqNDuBrPHlYGavebAgKlOEFeADSUL6xD
            +JVsh+xXSuhegMO5Q3rjqHhRjfeqo8+9uTZx27uH8hx3VBZm0dIsoa+l/ypWxCx1
            B5p45kuB/B6/FCcjaPTEdLLx98HJEha+pGRWPa9NmaT/FIwAj3w767OKUU/ghujU
            ukslunfo+J2SaoEP1dL/g4LrZkUmfyWqLw3K0jFxcFdR2kgsDtmD7fPCzUKo8BIU
            WS8xrKfhk8vx1s4a8oROC4M7LKSISrKeYC2/ZoWwfyTE4U2erWr5rgJzL4ym7TaD
            nEvi428AwTqoULoi9vWMglXgtww7GrfqWhMGrYu29sSpXZKCRZzBc/koha6PBnw8
            esHUzBDXqrfkO6z3aLCe0M23AzBx+c8sNWdMleJaHKUeC+0ocx7qyJd7hrhHh9/S
            9wIK9cKbBUvqbtzRjC5vCwhZHeLZAfWV0NDmgpsQSGe6DWpkklIiPgLUatsJtBtS
            Gy0b+Wbq8e54OZcW+8p7M26PrrJanRIRaXUSdN2nJFshv109dGSdYLo7UFYwQOPS
            XgGd45iMIV6MWE/7cG3eVAbO1YehVs8xz6jU6X0wx0YaP2wpw5GDmOegPIfyvBik
            I9yzgWG5ptCIHzXsE/OCWJQc9u4+thD5NbPCNKeOqi4SsGKNQ71GtoQNKx6lTkQ=
            =gfO2
            -----END PGP MESSAGE-----
          fp: CFEB9CF1BBFB6A79F2CD7DF90A421F34D04D10E2
    encrypted_regex: ^(data|stringData|addresses)$
    version: 3.10.2
