apiVersion: v1
kind: ConfigMap
metadata:
  name: karma-config
  namespace: monitoring
data:
  karma.yaml: |
    alertmanager:
      servers:
        - name: rpi-cluster-prod
          uri: http://kube-prometheus-stack-alertmanager.monitoring.svc:9093
