apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karma
  template:
    metadata:
      labels:
        app: karma
    spec:
      containers:
        - name: karma
          image: ghcr.io/prymitive/karma:v0.120
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/karma/karma.yaml
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: karma-config
              mountPath: /etc/karma
      volumes:
        - name: karma-config
          configMap:
            name: karma-config
