apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openbao
  namespace: openbao
spec:
  interval: 12h
  url: https://openbao.github.io/openbao-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  interval: 5m
  chart:
    spec:
      chart: openbao/openbao
      version: 0.18..2
      sourceRef:
        kind: HelmRepository
        name: openbao
        namespace: openbao
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: openbao.crulabs.internal
        tls:
          - secretName: ca-crulabs
            hosts:
              - openbao.crulabs.internal
     serverTelemetry:
       serviceMonitor:
         enabled: true
       prometheusRules:
         enabled: true
       grafanaDashboard:
         enabled: true
