apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
spec:
  interval: 12h
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  values:
    nfs:
      server: 192.168.34.46
      path: /srv/k8s-storage
    storageClass:
      name: nfs-rwx
      defaultClass: true
      reclaimPolicy: Retain
      accessModes: ReadWriteMany
      onDelete: retain
    leaderElection:
      enabled: true
