apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-alerts
  namespace: monitoring
spec:
  groups:
  - name: flux.rules
    rules:
    - alert: FluxGitRepositoryNotReady
      expr: |
        gotk_reconcile_condition{kind="GitRepository", type="Ready", status!="true"} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Flux GitRepository {{ $labels.name }} is not ready"
        description: |
          The GitRepository {{ $labels.name }} in namespace {{ $labels.namespace }}
          has not been ready for more than 5 minutes.

    - alert: FluxKustomizationNotReady
      expr: |
        gotk_reconcile_condition{kind="Kustomization", type="Ready", status!="true"} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Flux Kustomization {{ $labels.name }} is not ready"
        description: |
          The Kustomization {{ $labels.name }} in namespace {{ $labels.namespace }}
          has not been ready for more than 5 minutes.
