apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: flux-system
  labels:
    app: source-controller
spec:
  selector:
    app: source-controller
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-controller-metrics
  namespace: flux-system
  labels:
    app: notification-controller
spec:
  selector:
    app: notification-controller
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: helm-controller-metrics
  namespace: flux-system
  labels:
    app: helm-controller
spec:
  selector:
    app: helm-controller
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kustomize-controller-metrics
  namespace: flux-system
  labels:
    app: kustomize-controller
spec:
  selector:
    app: kustomize-controller
  ports:
    - name: http-prom
      port: 8080
      targetPort: http-prom
      protocol: TCP
