apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-controllers
  namespace: flux-system
  labels:
    prometheus: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector: {}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
