apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.34.204
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: pihole
